site_name: Gmaster Documentation
site_url: https://docs.gmaster.com
theme:
  name: material

nav:
  - 首页: index.md
  - 软件组:
      - 软件组首页: 软件组/index.md
      - 培训:
          - 培训首页: 软件组/培训/index.md
          - 自学清单: 软件组/培训/自学清单.md
          - Lesson1 开发环境配置: 软件组/培训/Lesson1 开发环境配置.md
          - Github Education认证: 软件组/培训/Github Education认证.md
          - C++基础:
              - C++基础首页: 软件组/培训/C++基础/index.md
              - 01 程序结构与基本语法: 软件组/培训/C++基础/01-程序结构与基本语法.md
              - 02 数据类型: 软件组/培训/C++基础/02-数据类型.md
              - 03 变量与常量: 软件组/培训/C++基础/03-变量与常量.md
              - 04 运算符: 软件组/培训/C++基础/04-运算符.md
              - 05 输入输出: 软件组/培训/C++基础/05-输入输出.md
              - 06 判断语句: 软件组/培训/C++基础/06-判断语句.md
              - 07 循环语句: 软件组/培训/C++基础/07-循环语句.md
              - 08 数组与字符串: 软件组/培训/C++基础/08-数组与字符串.md
              - 09 函数: 软件组/培训/C++基础/09-函数.md
              - 10 存储类与作用域: 软件组/培训/C++基础/10-存储类与作用域.md
          - C++进阶:
              - C++进阶首页: 软件组/培训/C++进阶/index.md
              - 指针: 软件组/培训/C++进阶/指针.md
              - 内存: 软件组/培训/C++进阶/内存.md
              - 面向对象编程: 软件组/培训/C++进阶/面向对象编程.md
              - 多态: 软件组/培训/C++进阶/多态.md
              - 模板template: 软件组/培训/C++进阶/模板template.md
              - 移动语义: 软件组/培训/C++进阶/移动语义.md
              - lambda表达式: 软件组/培训/C++进阶/lambda表达式.md
              - std::array: 软件组/培训/C++进阶/std_array.md
              - using别名: 软件组/培训/C++进阶/using别名.md
              - algorithm数学操作: 软件组/培训/C++进阶/algorithm数学操作.md
              - 行为树: 软件组/培训/C++进阶/行为树.md
          - 嵌入式基础:
              - 嵌入式基础首页: 软件组/培训/嵌入式基础/index.md
              - 01 嵌入式系统概述与HAL库: 软件组/培训/嵌入式基础/01-嵌入式系统概述与HAL库.md
              - 02 时钟树与总线架构: 软件组/培训/嵌入式基础/02-时钟树与总线架构.md
              - 03 GPIO与高低电平: 软件组/培训/嵌入式基础/03-GPIO与高低电平.md
              - 04 中断与NVIC: 软件组/培训/嵌入式基础/04-中断与NVIC.md
              - 05 回调机制与HAL中断处理: 软件组/培训/嵌入式基础/05-回调机制与HAL中断处理.md
              - 06 定时器与PWM: 软件组/培训/嵌入式基础/06-定时器与PWM.md
              - 07 舵机与电机: 软件组/培训/嵌入式基础/07-舵机与电机.md
              - 08 UART通信原理: 软件组/培训/嵌入式基础/08-UART通信原理.md
              - 09 SPI通信原理: 软件组/培训/嵌入式基础/09-SPI通信原理.md
              - 10 I2C通信原理: 软件组/培训/嵌入式基础/10-I2C通信原理.md
              - 11 CAN通信原理: 软件组/培训/嵌入式基础/11-CAN通信原理.md
              - 12 IMU姿态传感器: 软件组/培训/嵌入式基础/12-IMU姿态传感器.md
              - 13 GSRL工程结构与运行机制: 软件组/培训/嵌入式基础/13-GSRL工程结构与运行机制.md
      - 开发:
          - 开发首页: 软件组/开发/index.md
          - Git: 软件组/开发/Git.md
          - SSH: 软件组/开发/ssh.md
          - 烧录器: 软件组/开发/烧录器.md
          - LiveWatch: 软件组/开发/livewatch.md
          - UART线序: 软件组/开发/UART线序.md
          - CAN负载计算: 软件组/开发/CAN负载计算器.md
          - PID: 软件组/开发/PID.md
          - Vofa调试: 软件组/开发/Vofa.md
          - 电机手册: 软件组/开发/电机手册.md
          - 通信协议: 软件组/开发/通信协议.md
      - Checklist:
          - Checklist首页: 软件组/checklist/index.md
          - 电机: 软件组/checklist/电机.md
          - 烧录: 软件组/checklist/烧录.md
          - 串口读取数据: 软件组/checklist/串口读取数据.md
  - 硬件组: 硬件组/index.md
  - 机械组: 机械组/index.md
  - 视觉组: 视觉组/index.md
  - 宣运组: 宣运组/index.md
